version: '3.8'

services:
  realsense:
    image: realsense-ros-galactic
    container_name: realsense_container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    stdin_open: true
    tty: true

